Algoritmo "cosseno"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   :
// Descrição   : Calcular o cosseno
// Autor(a)    : Mayra Duarte
// Data atual  : 13/06/2023
Var
   // Seção de Declarações das variáveis
vlcos: real

Inicio
   // Declaração de variáveis
   
vlcos <-0

   // Seção de Comandos, procedimento, funções, operadores, etc...
 vlcos <- cos(30)
 escreval("O cosseno de [30] é [",vlcos,"]")

Fimalgoritmo